//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_MVC_EmployeeInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int EmployeeID { get; set; }
        public int NoteID { get; set; }
        public string Description { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
